import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  header: {
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 24,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#333",
    marginTop: 12,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 100,
  },
  currentPlanBanner: {
    backgroundColor: "#E8F5E9",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#65C879",
  },
  currentPlanHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  currentPlanTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#65C879",
    marginLeft: 8,
  },
  currentPlanName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333",
    marginBottom: 12,
  },
  currentPlanInfo: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  infoText: {
    fontSize: 14,
    color: "#666",
    marginLeft: 6,
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF9E6",
    padding: 12,
    borderRadius: 8,
    marginTop: 12,
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: "#F5A623",
    marginLeft: 8,
    lineHeight: 18,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#333",
    marginBottom: 16,
  },
  planCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  planCardCurrent: {
    borderWidth: 2,
    borderColor: "#E0E0E0",
    opacity: 0.7,
  },
  badgeContainer: {
    marginBottom: 16,
  },
  currentChip: {
    alignSelf: "flex-start",
    backgroundColor: "#E8F5E9",
  },
  currentChipText: {
    color: "#65C879",
    fontWeight: "600",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#FFF9E6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#F5A623",
    marginLeft: 4,
  },
  planHeader: {
    marginBottom: 20,
  },
  planName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333",
    marginBottom: 8,
  },
  planDescription: {
    fontSize: 15,
    color: "#666",
    lineHeight: 22,
  },
  priceContainer: {
    backgroundColor: "#F8F9FA",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 24,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  priceCurrency: {
    fontSize: 24,
    fontWeight: "600",
    color: "#65C879",
    marginRight: 4,
  },
  price: {
    fontSize: 40,
    fontWeight: "700",
    color: "#65C879",
  },
  pricePeriod: {
    fontSize: 18,
    color: "#999",
    marginLeft: 4,
  },
  priceCustom: {
    fontSize: 28,
    fontWeight: "700",
    color: "#65C879",
    marginBottom: 4,
  },
  priceSubtext: {
    fontSize: 14,
    color: "#999",
  },
  characteristicsContainer: {
    marginBottom: 24,
  },
  characteristicsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 16,
  },
  characteristicItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  iconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  characteristicText: {
    flex: 1,
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  characteristicName: {
    fontWeight: "600",
    color: "#333",
  },
  buttonContent: {
    paddingVertical: 8,
  },
  activeButton: {
    borderRadius: 8,
    borderColor: "#E0E0E0",
    borderWidth: 1.5,
    backgroundColor: "#F5F5F5",
  },
  activeButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#999",
  },
  selectButton: {
    backgroundColor: "#65C879",
    borderRadius: 8,
    elevation: 2,
  },
  selectButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
  },
  infoButton: {
    borderRadius: 8,
    borderColor: "#65C879",
    borderWidth: 1.5,
  },
  infoButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#65C879",
  },
  contactButton: {
    borderRadius: 8,
    borderColor: "#25D366",
    borderWidth: 1.5,
  },
  contactButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#25D366",
  },
  footerInfo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 16,
  },
  footerText: {
    flex: 1,
    fontSize: 14,
    color: "#666",
    marginLeft: 12,
    lineHeight: 20,
  },
  footerButton: {
    marginTop: 8,
  },
  footerButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#65C879",
  },
});